// <auto-generated />
using System;
using FillialeData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FillialeData.Migrations
{
    [DbContext(typeof(FillialeContext))]
    partial class FillialeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FillialeDomain.Models.Filliale", b =>
                {
                    b.Property<Guid>("FillialeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FillialeCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FillialeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FillialeId");

                    b.HasIndex("FillialeCode")
                        .IsUnique();

                    b.HasIndex("FillialeId")
                        .IsUnique();

                    b.ToTable("Filliale");
                });
#pragma warning restore 612, 618
        }
    }
}
